import { Region } from "@/types/regions";

export const REGIONS: Region[] = [
  {
    id: "US",
    name: "United States",
    aliases: ["usa", "us", "america", "united states", "new york", "los angeles"],
    coords: [-95.7, 37.1],
    playlistId: "37i9dQZEVXbLRQDuF5jeBp",
    genre: "Pop / Hip-Hop",
    pinColor: "#3B82F6",
    country: "US",
  },
  {
    id: "BR",
    name: "Brazil",
    aliases: ["brazil", "brasil", "rio", "sao paulo", "brazilian"],
    coords: [-51.9, -14.2],
    playlistId: "37i9dQZEVXbMXbN3EUUhlg",
    genre: "Funk / Sertanejo",
    pinColor: "#22C55E",
    country: "BR",
  },
  {
    id: "NG",
    name: "Nigeria",
    aliases: ["nigeria", "nigerian", "afrobeats", "lagos", "abuja"],
    coords: [8.7, 9.1],
    playlistId: "37i9dQZEVXbKY7jLzlJ11V",
    genre: "Afrobeats",
    pinColor: "#F59E0B",
    country: "NG",
  },
  {
    id: "JP",
    name: "Japan",
    aliases: ["japan", "japanese", "j-pop", "jpop", "tokyo", "osaka"],
    coords: [138.3, 36.2],
    playlistId: "37i9dQZEVXbKXQ4mDTEBXq",
    genre: "J-Pop",
    pinColor: "#EC4899",
    country: "JP",
  },
  {
    id: "IN",
    name: "India",
    aliases: ["india", "indian", "bollywood", "mumbai", "delhi", "bangalore"],
    coords: [78.9, 20.6],
    playlistId: "37i9dQZEVXbLZ52XmnySJg",
    genre: "Bollywood",
    pinColor: "#F97316",
    country: "IN",
  },
  {
    id: "KR",
    name: "South Korea",
    aliases: ["korea", "south korea", "k-pop", "kpop", "seoul", "korean"],
    coords: [127.8, 35.9],
    playlistId: "37i9dQZEVXbNxXF4SkHj9F",
    genre: "K-Pop",
    pinColor: "#A855F7",
    country: "KR",
  },
  {
    id: "CO",
    name: "Colombia",
    aliases: ["colombia", "colombian", "reggaeton", "cumbia", "bogota", "medellin"],
    coords: [-74.3, 4.6],
    playlistId: "37i9dQZEVXbOa2lmxNORXQ",
    genre: "Reggaeton / Cumbia",
    pinColor: "#EF4444",
    country: "CO",
  },
  {
    id: "MX",
    name: "Mexico",
    aliases: ["mexico", "mexican", "mexico city", "monterrey", "guadalajara"],
    coords: [-102.6, 23.6],
    playlistId: "37i9dQZEVXbO3qyFxbkOFB",
    genre: "Latin Pop",
    pinColor: "#EF4444",
    country: "MX",
  },
  {
    id: "GB",
    name: "United Kingdom",
    aliases: ["uk", "united kingdom", "britain", "england", "london", "british"],
    coords: [-3.4, 54.4],
    playlistId: "37i9dQZEVXbLnolsZ8PSNw",
    genre: "UK Pop",
    pinColor: "#3B82F6",
    country: "GB",
  },
  {
    id: "DE",
    name: "Germany",
    aliases: ["germany", "german", "berlin", "munich", "deutsche"],
    coords: [10.5, 51.2],
    playlistId: "37i9dQZEVXbJiZcmkrIHGU",
    genre: "Schlager / Pop",
    pinColor: "#6B7280",
    country: "DE",
  },
  {
    id: "FR",
    name: "France",
    aliases: ["france", "french", "paris", "marseille", "français"],
    coords: [2.3, 46.2],
    playlistId: "37i9dQZEVXbIPWwFssbupI",
    genre: "French Pop",
    pinColor: "#3B82F6",
    country: "FR",
  },
  {
    id: "ES",
    name: "Spain",
    aliases: ["spain", "spanish", "madrid", "barcelona", "flamenco"],
    coords: [-3.7, 40.4],
    playlistId: "37i9dQZEVXbNFJfN1Vw8d9",
    genre: "Latin / Flamenco",
    pinColor: "#EF4444",
    country: "ES",
  },
  {
    id: "ZA",
    name: "South Africa",
    aliases: ["south africa", "south african", "johannesburg", "cape town", "amapiano"],
    coords: [25.1, -29.0],
    playlistId: "37i9dQZEVXbMH2jvi6jvjk",
    genre: "Amapiano / Afro",
    pinColor: "#F59E0B",
    country: "ZA",
  },
  {
    id: "GH",
    name: "Ghana",
    aliases: ["ghana", "ghanaian", "accra", "highlife", "afropop"],
    coords: [-1.0, 7.9],
    playlistId: "37i9dQZEVXbLhtMoaD8zLl",
    genre: "Highlife / Afropop",
    pinColor: "#F59E0B",
    country: "GH",
  },
  {
    id: "AR",
    name: "Argentina",
    aliases: ["argentina", "argentinian", "buenos aires", "tango"],
    coords: [-63.6, -38.4],
    playlistId: "37i9dQZEVXbMMy2roB9myp",
    genre: "Tango / Pop",
    pinColor: "#6366F1",
    country: "AR",
  },
  {
    id: "CL",
    name: "Chile",
    aliases: ["chile", "chilean", "santiago", "chilena"],
    coords: [-71.5, -35.7],
    playlistId: "37i9dQZEVXbL0GavIqMTeb",
    genre: "Pop / Rock",
    pinColor: "#EF4444",
    country: "CL",
  },
  {
    id: "TR",
    name: "Turkey",
    aliases: ["turkey", "turkish", "istanbul", "ankara", "türk"],
    coords: [35.2, 38.9],
    playlistId: "37i9dQZEVXbIVYVBNw9UsY",
    genre: "Turkish Pop",
    pinColor: "#EF4444",
    country: "TR",
  },
  {
    id: "EG",
    name: "Egypt",
    aliases: ["egypt", "egyptian", "cairo", "arabic", "arab"],
    coords: [30.8, 26.8],
    playlistId: "37i9dQZEVXbLn7RQmT5Wv3",
    genre: "Arabic Pop",
    pinColor: "#F59E0B",
    country: "EG",
  },
  {
    id: "ID",
    name: "Indonesia",
    aliases: ["indonesia", "indonesian", "jakarta", "bali"],
    coords: [113.9, -0.8],
    playlistId: "37i9dQZEVXbObFQZ3JLcXt",
    genre: "Pop / Dangdut",
    pinColor: "#EF4444",
    country: "ID",
  },
  {
    id: "PH",
    name: "Philippines",
    aliases: ["philippines", "filipino", "manila", "opm"],
    coords: [121.8, 12.9],
    playlistId: "37i9dQZEVXbMnZEatlMSiu",
    genre: "OPM",
    pinColor: "#3B82F6",
    country: "PH",
  },
  {
    id: "TH",
    name: "Thailand",
    aliases: ["thailand", "thai", "bangkok", "t-pop"],
    coords: [101.0, 15.9],
    playlistId: "37i9dQZEVXbMnz8KIWsvf9",
    genre: "T-Pop",
    pinColor: "#A855F7",
    country: "TH",
  },
  {
    id: "AU",
    name: "Australia",
    aliases: ["australia", "australian", "sydney", "melbourne", "aussie"],
    coords: [133.8, -25.3],
    playlistId: "37i9dQZEVXbJPcfkRz0wJ0",
    genre: "Indie / Pop",
    pinColor: "#22C55E",
    country: "AU",
  },
  {
    id: "IT",
    name: "Italy",
    aliases: ["italy", "italian", "rome", "milan", "italia"],
    coords: [12.6, 41.9],
    playlistId: "37i9dQZEVXbIQnj7RRhdSX",
    genre: "Italian Pop",
    pinColor: "#22C55E",
    country: "IT",
  },
  {
    id: "NG_AMAPIANO",
    name: "West Africa",
    aliases: ["west africa", "afro house", "senegal", "mali", "dakar"],
    coords: [-12.4, 12.4],
    playlistId: "37i9dQZEVXbLhtMoaD8zLl",
    genre: "Afro House",
    pinColor: "#F59E0B",
    country: "SN",
  },
  {
    id: "JM",
    name: "Jamaica",
    aliases: ["jamaica", "jamaican", "reggae", "dancehall", "kingston"],
    coords: [-77.3, 18.1],
    playlistId: "37i9dQZEVXbKj23U1GF4IR",
    genre: "Reggae / Dancehall",
    pinColor: "#22C55E",
    country: "JM",
  },
  {
    id: "PT",
    name: "Portugal",
    aliases: ["portugal", "portuguese", "lisbon", "fado", "porto"],
    coords: [-8.2, 39.4],
    playlistId: "37i9dQZEVXbKyJS56zrk0x",
    genre: "Fado / Pop",
    pinColor: "#EF4444",
    country: "PT",
  },
  {
    id: "SE",
    name: "Sweden",
    aliases: ["sweden", "swedish", "stockholm", "nordic", "scandinavian"],
    coords: [18.6, 62.2],
    playlistId: "37i9dQZEVXbLoATJ81NtNp",
    genre: "Swedish Pop",
    pinColor: "#3B82F6",
    country: "SE",
  },
  {
    id: "NG_JUJU",
    name: "East Africa",
    aliases: ["east africa", "kenya", "ethiopia", "nairobi", "addis ababa"],
    coords: [37.9, 0.0],
    playlistId: "37i9dQZEVXbKY7jLzlJ11V",
    genre: "Bongo / Benga",
    pinColor: "#22C55E",
    country: "KE",
  },
  {
    id: "RU",
    name: "Russia",
    aliases: ["russia", "russian", "moscow", "st petersburg"],
    coords: [105.3, 61.5],
    playlistId: "37i9dQZEVXbNmwM1PXGMaD",
    genre: "Russian Pop",
    pinColor: "#EF4444",
    country: "RU",
  },
  {
    id: "CN",
    name: "China",
    aliases: ["china", "chinese", "beijing", "shanghai", "c-pop", "mandarin"],
    coords: [104.2, 35.9],
    playlistId: "37i9dQZEVXbLwpL8TjsxOc",
    genre: "C-Pop / Mandopop",
    pinColor: "#EF4444",
    country: "CN",
  },
];

export function findRegionByQuery(query: string): Region | undefined {
  const q = query.toLowerCase().trim();
  return REGIONS.find(
    (r) =>
      r.id.toLowerCase() === q ||
      r.name.toLowerCase() === q ||
      r.aliases.some((a) => a.includes(q) || q.includes(a))
  );
}

export function findRegionById(id: string): Region | undefined {
  return REGIONS.find((r) => r.id === id);
}
